### ISSUE TITLE
allbiomes.py not running on main branch

### ISSUE THREAD

**Issue by caranha** [MightyCode/GDMC2021Tsukuba#10]
```
caranha@paraponera:~/Work/Project_GDMC/GDMC2021Tsukuba$ python ./allbiomes.py

Traceback (most recent call last):
  File "./allbiomes.py", line 2, in <module>
    from _ressources import *
ModuleNotFoundError: No module named '_ressources'
```

**Comment by Harckyl** [comment]
i did several things monday and tuesday not touching that because i try to implement the floodfill algorithm and i have now the same issues with allbiomes and an other program i'm writing, i don't know yet what's causing it

**Comment by Harckyl** [comment]
oh i think just the class had an S missing and is called resources
