### ISSUE TITLE
Generate "Quarry"

### ISSUE THREAD

**Issue by caranha** [MightyCode/GDMC2021Tsukuba#19]
Function to generate a Quarry (Hole in the ground)

- The function receives location and biome as parameters (other parameters might be added later)
- Function creates a large hole in the ground, and the necessary "decorations" -- fence around the hole, stairs down, etc.
- The function counts how many "stone" and "ore" blocks were excavated, and returns this information

Remember to add small randomness to the quarry -- for example, different locations for torches, different decorations, etc.

One easy way to do this, for example, is always adding 10 torches, but then removing 4 of them randomly.

**Comment by MightyCode** [comment]
Now fix the problem of chest and water
